"""Auto migration

Revision ID: 28b626b42cef
Revises: d5489fb4804a
Create Date: 2025-09-16 22:19:04.291057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b626b42cef'
down_revision = 'd5489fb4804a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_url', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['calendar_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('calendar_url')

    # ### end Alembic commands ###
