"""Auto migration

Revision ID: 3580ab02dc27
Revises: 
Create Date: 2025-02-23 07:13:09.356289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3580ab02dc27'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift'], ['shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('shifts_event_fkey', type_='foreignkey')
        batch_op.drop_constraint('shifts_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shifts_user_fkey', 'user', ['user'], ['id'])
        batch_op.create_foreign_key('shifts_event_fkey', 'events', ['event'], ['id'])
        batch_op.alter_column('end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=False)

    op.drop_table('duty')
    # ### end Alembic commands ###
