"""Auto migration

Revision ID: 426ad42e1145
Revises: 68cad9b0dccd
Create Date: 2025-04-06 02:10:57.537443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426ad42e1145'
down_revision = '68cad9b0dccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
