"""Auto migration

Revision ID: 49e7b3ae2559
Revises: a4e364e37b35
Create Date: 2025-03-19 01:24:20.383927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e7b3ae2559'
down_revision = 'a4e364e37b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registermanager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deny', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registermanager', schema=None) as batch_op:
        batch_op.drop_column('deny')

    # ### end Alembic commands ###
