"""Auto migration

Revision ID: 829bb0e37a4e
Revises: dc0720bcb32b
Create Date: 2025-03-26 11:12:28.004766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829bb0e37a4e'
down_revision = 'dc0720bcb32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registermanager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registermanager', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
