"""Auto migration

Revision ID: a4e364e37b35
Revises: 782d662b163b
Create Date: 2025-03-11 20:26:17.269965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e364e37b35'
down_revision = '782d662b163b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registermanager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=True),
    sa.Column('accept', sa.String(length=12), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('eventFK', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventFK'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userFK', sa.Integer(), nullable=True),
    sa.Column('rmFK', sa.Integer(), nullable=True),
    sa.Column('teamname', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['rmFK'], ['registermanager.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userFK'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('creation')

    op.drop_table('registration')
    op.drop_table('registermanager')
    # ### end Alembic commands ###
