"""Auto migration

Revision ID: d5489fb4804a
Revises: 426ad42e1145
Create Date: 2025-04-08 00:54:10.763029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5489fb4804a'
down_revision = '426ad42e1145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eventFK', sa.Integer(), nullable=True),
    sa.Column('authorFK', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('timeframe_start', sa.DateTime(), nullable=True),
    sa.Column('timeframe_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorFK'], ['user.id'], ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['eventFK'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userFK', sa.Integer(), nullable=True),
    sa.Column('taskFK', sa.Integer(), nullable=True),
    sa.Column('joined_timestamp', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['taskFK'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userFK'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty', schema=None) as batch_op:
        batch_op.drop_constraint('duty_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('events_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('howto', schema=None) as batch_op:
        batch_op.drop_constraint('howto_userFK_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userFK'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('howto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('howto_userFK_fkey', 'user', ['userFK'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_author_fkey', 'user', ['author'], ['id'])

    with op.batch_alter_table('duty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('duty_user_fkey', 'user', ['user'], ['id'])

    op.drop_table('assistant')
    op.drop_table('task')
    # ### end Alembic commands ###
