"""Auto migration

Revision ID: dc0720bcb32b
Revises: 49e7b3ae2559
Create Date: 2025-03-25 03:14:44.517066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0720bcb32b'
down_revision = '49e7b3ae2559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('howto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userFK', sa.Integer(), nullable=True),
    sa.Column('header', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['userFK'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('valid')
        batch_op.drop_column('paid')
        batch_op.drop_column('price')

    op.drop_table('howto')
    # ### end Alembic commands ###
