services:
  database:
    ports:
        - 5432:5432 # for development reasons
    build: ./database-server
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: ./flask-server 
    ports:
      - 5005:80
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URI=postgresql://postgres:${DATABASE_PASSWORD}@database/postgres
      - SECRET_KEY=${SECRET_KEY}

    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl -fs http://localhost 2>&1 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build: ./test
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
      flask:
        condition: service_healthy
    profiles:
      - test

volumes:
  pgdata:
