services:
  database:
    image: ./database-server 
    restart: always
    volumes:
      - ./database/:/var/database/:rw
    environment:
      - POSTGRES_DB="postgres"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: ./flask-server 
    ports:
      - 5005:80
    environment:
      - DATABASE_HOST="database"
      - DATABASE_PORT="5432"
      - DATABASE_NAME="postgres"
      - DATABASE_USER="postgres"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
    depends_on:
      database:
        condition: service_healthy

  test:
    build: ./test
    environment:
      - DATABASE_HOST="database"
      - DATABASE_PORT="5432"
      - DATABASE_NAME="postgres"
      - DATABASE_USER="postgres"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
    depends_on:
      database:
        condition: service_healthy
      flask:
        condition: service_started
    profiles:
      - test
