services:
  database:
    build: ./database-server
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build: ./flask-server 
    ports:
      - 5005:80
      - "127.0.0.1:9191:9191"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}
      - DEFAULT_USER=${DEFAULT_USER}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
      - DROP_DATABASE=false
      - CREATE_DATABASE=true
      - Debug=false

    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl -fs http://localhost 2>&1 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build: ./test
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
      flask:
        condition: service_healthy
    profiles:
      - test

volumes:
  pgdata:
