name: Test Code

on:
  push:
    branches-ignore:
      - '26-container-needed'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Login'
        run: 'docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io'

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "sia-backend/compose.yml"
          compose-flags: "--profile debug"
     
      - name: 'Logout'
        run: 'docker logout ghcr.io'